global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Reflection;
global using Microsoft.AspNetCore.Identity;
global using _2B_Egypt.Domain.Models;
global using _2B_Egypt.Infrastructure.Context;
global using _2B_Egypt.Application.IRepositories;
global using _2B_Egypt.Infrastructure.Context.Configurations;